# Generated by Django 5.2.8 on 2025-11-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=6)),
                ('is_won', models.BooleanField(default=False)),
            ],
        ),
    ]
